- sample/Sample/RecycleItemsView/ColumnTest.xaml
- sample/Sample/RecycleItemsView/ColumnTest.xaml.cs
- sample/Sample/RecycleItemsView/RecycleItemsViewModel.cs
- sample/Sample/Sample.csproj
- src/Tizen.TV.UIControls.Forms/RecycleItemsView.cs
This PR is impelementation for supporting multiple columns in RecycleItemsView
* Added
``` c#
public class RecycleItemsView {
public int ColumnCount
}
```
> [Enhancement] Support multiple Columns in RecycleItemsView

- src/Tizen.TV.UIControls.Forms/IPlatformMediaPlayer.cs
- src/Tizen.TV.UIControls.Forms/IVideoOutput.cs
- src/Tizen.TV.UIControls.Forms/InputEvents.cs
- src/Tizen.TV.UIControls.Forms/MediaPlayer.cs
- src/Tizen.TV.UIControls.Forms/MediaSource.cs
- src/Tizen.TV.UIControls.Forms/MediaView.cs
- src/Tizen.TV.UIControls.Forms/OverlayMediaView.cs
- src/Tizen.TV.UIControls.Forms/OverlayPage.cs
- src/Tizen.TV.UIControls.Forms/PlaybackState.cs
- src/Tizen.TV.UIControls.Forms/RemoteControlKeyEventArgs.cs
- src/Tizen.TV.UIControls.Forms/RemoteControlKeyNames.cs
- src/Tizen.TV.UIControls.Forms/RemoteControlKeyTypes.cs
- src/Tizen.TV.UIControls.Forms/RemoteKeyHandler.cs
Add documentation for media and input events features.
Some comments may need to be more improved.
> Add documentation on each public classed

- CODE_OF_CONDUCT.md
> Adds CODE_OF_CONDUCT.md

- src/Tizen.TV.UIControls.Forms/FileMediaSource.cs
- src/Tizen.TV.UIControls.Forms/FileMediaSourceConverter.cs
- src/Tizen.TV.UIControls.Forms/MediaSourceConverter.cs
- src/Tizen.TV.UIControls.Forms/RecycleItemsView.cs
- src/Tizen.TV.UIControls.Forms/Renderer/RecycleItemsViewRenderer.cs
- src/Tizen.TV.UIControls.Forms/UriMediaSource.cs
* Update Docs of RecycleItemsView
None
None
None
> Update Docs of RecycleItemsView

- src/Tizen.TV.UIControls.Forms/Tizen.TV.UIControls.Forms.csproj
More package information that should be added to the genreated nuspec is added.
Added package information:
- authors
- owners
- icon url
- tags
N/A
N/A
N/A
> Add more package information on csproj

- docs/guides/Overview.md
Add quotation marks for img tags on Guides page to show the image.
N/A
N/A
N/A
> Fix the image source on guides page

- README.md
- docs/guides/Overview.md
Fix typo on README and Guides page.
N/A
N/A
N/A
> Fix typo on README and Guides

- src/Tizen.TV.UIControls.Forms/MediaPlayer.cs
- src/Tizen.TV.UIControls.Forms/OverlayPage.cs
- src/Tizen.TV.UIControls.Forms/RecycleItemsView.cs
- src/Tizen.TV.UIControls.Forms/Renderer/MediaPlayerImpl.cs
- src/Tizen.TV.UIControls.Forms/Renderer/OverlayPageRenderer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/RecycleItemsViewRenderer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/UIControls.cs
Fix review point by codacy
None
None
None
> Fix codacy review

- sample/Sample/Focus/FocusBasicTest.xaml
- sample/Sample/Focus/FocusBasicTest.xaml.cs
- sample/Sample/Focus/FocusMainPage.xaml
- sample/Sample/Focus/FocusMainPage.xaml.cs
- sample/Sample/Focus/FocusScrollTest.xaml
- sample/Sample/Focus/FocusScrollTest.xaml.cs
- sample/Sample/Focus/FocusTest2.xaml
- sample/Sample/Focus/FocusTest2.xaml.cs
- sample/Sample/Focus/FocusTest3.xaml
- sample/Sample/Focus/FocusTest3.xaml.cs
- sample/Sample/Focus/FocusTestModel.cs
- sample/Sample/MainPageModel.cs
- sample/Sample/Sample.csproj
- src/Tizen.TV.UIControls.Forms/Focus.cs
- src/Tizen.TV.UIControls.Forms/RemoteControlKeyEventArgs.cs
- src/Tizen.TV.UIControls.Forms/Renderer/PlatformFocusEffect.cs
- src/Tizen.TV.UIControls.Forms/Renderer/RemoteKeyEventEffect.cs
Introduce custom focus management API
https://github.com/Samsung/Tizen.TV.UIControls/issues/30
Added:
* Attached Property
* Focus.UpProperty
* Focus.DownProperty
* Focus.LeftProperty
* Focus.RightProperty
> Add Custom Focus API

- docs/guides/Troubleshooter.md
- docs/guides/toc.md
Add a guide page explaining that this package replaces renderers for `Entry` and `Editor` to fix the input panel issues.
- N/A
- N/A
- N/A
> Add guide page explaning Entry and Editor

- sample/TMDb/src/TMDb/TMDb/DetailPage.xaml.cs
- sample/TMDb/src/TMDb/TMDb/MainPage.xaml.cs
- sample/TMDb/src/TMDb/TMDb/TMDbAPIKey.cs
Remove API key from sample code
None
None
None
> Update API key from Sample

- src/Tizen.TV.UIControls.Forms/Tizen.TV.UIControls.Forms.csproj
> Update package icon url

- sample/Sample.Tizen/Sample.Tizen.cs
- sample/Sample/MediaPlayer/SimplePlayerPage.xaml
- sample/Sample/MediaPlayer/SimplePlayerPage.xaml.cs
- sample/Sample/MediaPlayer/TestOverlayView.xaml
- sample/Sample/Sample.csproj
- src/Tizen.TV.UIControls.Forms/Renderer/LayoutCanvas.cs
- src/Tizen.TV.UIControls.Forms/Renderer/MediaViewRenderer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/OverlayPageRenderer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/OverlayViewRenderer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/RecycleItemsViewRenderer.cs
- src/Tizen.TV.UIControls.Forms/Tizen.TV.UIControls.Forms.csproj
Upgrade Xamarin.forms version to 4.3.0
None
> Xamarin.forms version upgrade

- sample/Sample.Tizen/Sample.Tizen.csproj
- sample/Sample/Sample.csproj
- src/Tizen.TV.UIControls.Forms/RecycleItemsView.cs
- src/Tizen.TV.UIControls.Forms/Tizen.TV.UIControls.Forms.csproj
Update X.Forms version to 4.4.0.991537 and Tizen.NET.Sdk version 1.0.9.
> Update X.Forms version to 4.4.0.991537

- src/Tizen.TV.UIControls.Forms/Renderer/OverlayPageRenderer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/OverlayViewRenderer.cs
Change an accessibility of OverlayViewRenderer and OverlayPageRenderer
None
Changed:
- class OverlayPageRenderer => public class OverlayPageRenderer
- class OverlayViewRenderer=> public class OverlayViewRenderer
Extend the accessibility of Renderers for custom renderer.
> Change an accessibility of OverlayViewRenderer and OverlayPageRenderer

- sample/Sample/Focus/FocusTest2.xaml
Fix Focus Test2 sample code
- Focus was not changed to the next focused object
None
None
> Fix Focus Test2 sample

- src/Tizen.TV.UIControls.Forms/Tizen.TV.UIControls.Forms.csproj
This PR is fixing the vs project file(*.csproj) to load target(*.target) and theme(*.edj) into package(*.nupkg) correctly.
None
None
None
> Fix TV.UIControls.Forms.csproj correctly

- sample/Sample.Tizen/tizen-manifest.xml
- sample/Sample/Sample.csproj
- sample/TMDb/src/TMDb/TMDb/TMDb.csproj
- src/Tizen.TV.UIControls.Forms/Renderer/MediaPlayerImpl.cs
- src/Tizen.TV.UIControls.Forms/Tizen.TV.UIControls.Forms.csproj
This PR is to update the Xamarin.Forms version to 5.0.0-pre6. Accordingly, the samples were also changed.
- None
None
None
> Update Xamarin.Forms version to 5.0.0-pre6

- src/Tizen.TV.UIControls.Forms/GridView.cs
Remove unused `GridViewOrientation` enum.
> Remove unused GridViewOrientation

- src/Tizen.TV.UIControls.Forms/ITVESPlayer.cs
- src/Tizen.TV.UIControls.Forms/MediaPlayer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/AccessKeyEffect.cs
- src/Tizen.TV.UIControls.Forms/Renderer/ContentPopupRenderer.cs
- src/Tizen.TV.UIControls.Forms/Renderer/MediaPlayerImpl.cs
- src/Tizen.TV.UIControls.Forms/Renderer/RemoteKeyEventEffect.cs
- src/Tizen.TV.UIControls.Forms/Renderer/TVESExtensions.cs
- src/Tizen.TV.UIControls.Forms/Renderer/TVESPlayerImpl.cs
- src/Tizen.TV.UIControls.Forms/TVESEnumerations.cs
- src/Tizen.TV.UIControls.Forms/TVESEventArgs.cs
- src/Tizen.TV.UIControls.Forms/TVESPlayer.cs
- src/Tizen.TV.UIControls.Forms/Tizen.TV.UIControls.Forms.csproj
Add the ESPlayer
N/A
Added: TVESPlayer class
N/A
> Support the ESPlayer for playing element stream on TV

- src/Tizen.Theme.Common/Tizen.Theme.Common.csproj
Fix package version correctly to Tizen.Theme.Common
> Fix package version correctly to Tizen.Theme.Common

- docs/docfx/api/index.md
- docs/docfx/docfx.json
- docs/docfx/index.md
- docs/guides/Overview.md
- docs/guides/toc.md
This PR updates docs to add Tizen.Theme.Common to [API Reference](https://samsung.github.io/Tizen.TV.UIControls/index.html).
Once you add or update contents, TizenAPI-Bot will do the rest updating changes.
- [Main index page](https://samsung.github.io/Tizen.TV.UIControls/index.html)
-  Update `docs\docfx\index.md`
- [REFERENCES](https://samsung.github.io/Tizen.TV.UIControls/api/index.html)
- Update `docs\docfx\api\index.md`
- [GUIDES](https://samsung.github.io/Tizen.TV.UIControls/guides/Overview.html)
- Update `docs\docfx\api\index.md`
- Adding items at [Guides](https://samsung.github.io/Tizen.TV.UIControls/guides/Overview.html)
1. Write a new guide(.md) and locate file in `docs\guides\`
2. Update `docs\guides\toc.md` file to show up your guide to a content list.
- N/A
- None
- None
> Update docs to add Tizen.Theme.Common to reference

- README.md
Update README.md to add Tizen.Theme.Common.
> Update README to add Tizen.Theme.Common

- sample/Sample/ShadowFrame/ShadowFrameTest.xaml
- sample/Sample/ShadowFrame/ShadowFrameTest.xaml.cs
- src/Tizen.Theme.Common/Renderer/ShadowFrameRenderer.cs
- src/Tizen.Theme.Common/ShadowFrame.cs
This PR adds the `AllowShadowClipping` and `ShadowClippingWidth` to the ShadowFrame.
- None
Added:
- public bool ShadowFrame.AllowShadowClipping {get; set;} //Bindable Proerty
- public double ShadowFrame.ShadowClippingWidth{get; set;} //Bindable Proerty
None
> [CommonUI] Added AllowShadowClipping to ShadowFrame
